

DELETE http://localhost:3001/api/persons/2

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Deaken",
    //"name": "Ada Lovelace",
    "number": "020-12345"
}

###

POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "name": "XX",
    "number": "000-00000001"
}

###

Get http://localhost:3002/api/persons

###

DELETE  http://localhost:3002/api/persons/84dfd10c734df401f2821a5d

###

Get http://localhost:3002/api/persons/84dfd10c734df401f2821a5dhh

###

Post http://localhost:3002/api/personlist

###

Get http://localhost:3002/api/persons/64f4ee7082b1ea9bee04a3d6

###

PUT http://localhost:3002/api/persons/64f4e7db5d6d238c824ffa0f
Content-Type: application/json

{
    "name": "XXX5",
    "number":"000-00000005"
}

###

