

DELETE http://localhost:3001/api/persons/2

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Deaken",
    //"name": "Ada Lovelace",
    "number": "020-12345"
}

###

POST http://localhost:3002/api/persons
Content-Type: application/json

{
    "name": "XXX1",
    "number": "000-00001"
}

###

Get http://localhost:3002/api/persons

###

Get http://localhost:3002/api/persons/84dfd10c734df401f2821a5d

###

Post http://localhost:3002/api/personlist